apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  hosts: 
  - test.com
  gateways:
    - {{ .Values.virtualService.ingressGatewayName }}
  http:
    - match:
        - uri:
            prefix: /ggoginashvili
      route:
        - destination:
            host: {{ .Values.service.name }}
            port:
              number: 80